### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nathaneastwood** [nathaneastwood/euler#12]
So far the majority of problems (all of them?!) that we have solved don't have any form of explanation as to _why_ or _how_ they work. The code also contains very little comments. We could do with explaining our thought processes through the form of either short blogs or vignettes. What do you think @thisisnic?

**Comment by thisisnic** [comment]
Yup, was thinking this as I was reading through some of your solutions, as the code is well-written, but took me some time to figure out _why_ you'd done things a certain way.  I'd definitely be in favour of doing this.  My preference would be blog posts.

**Comment by nathaneastwood** [comment]
Where would they live? I feel there is a case here to have them live in both our personal blogs and as vignettes? I'm a fan of keeping everything related in the same package. 

Thinking about it, we could just have one vignette and then have each piece pulled out as a separate blog?

Or...we could use one of [`pkgdown`](https://github.com/r-lib/pkgdown), [`blogdown`](https://github.com/rstudio/blogdown) or (my personal preference) [`book down`](https://github.com/rstudio/bookdown)? Vignettes tend to be a "how to use this package" type of documentation.

**Comment by thisisnic** [comment]
I'm fine with both - I would like to blog about this, although not sure if I want to clutter up my blog with each and every single one?

Another issue is the following text on the Project Euler site:

> I learned so much solving problem XXX so is it okay to publish my solution elsewhere?
> 
> It appears that you have answered your own question. There is nothing quite like that "Aha!" moment when you finally beat a problem which you have been working on for some time. It is often through the best of intentions in wishing to share our insights so that others can enjoy that moment too. Sadly, however, that will not be the case for your readers. Real learning is an active process and seeing how it is done is a long way from experiencing that epiphany of discovery. Please do not deny others what you have so richly valued yourself.

**Comment by nathaneastwood** [comment]
Yeah that's a good point. But then people have the choice, they don't have to look at our solutions. Simply by posting them in this package gives them the ability to "cheat" and they're only cheating themselves by viewing them ;)

I feel that `bookdown` would be the best option. Simply because you can order them easily and there is much less maintenance than a blog. I'll set something up tonight and then we can always change it if we feel it doesn't work.

**Comment by thisisnic** [comment]
In light of discovering the text above on the Project Euler site, I'm no longer comfortable blogging about answers to specific problems, although would be happy to contribute towards more general content about solving maths problems (e.g. efficient code solutions for finding primes) in R if not linked to specific problems.  If you wish to go ahead with the solutions, then I won't be contributing to those, but still happy to contribute to this package in other ways.

**Comment by nathaneastwood** [comment]
Yes, I agree with this. Let's stick to documenting maths problems as opposed to Euler problems :)

**Comment by nathaneastwood** [comment]
I have added some information about this in d97dba7
