### ISSUE TITLE
recursive solution to euler 2

### ISSUE THREAD

**Issue by adfi** [nathaneastwood/euler#5]
I liked @thisisnic 's solution, didn't think of that myself. My mind went straight to a recursive solution:
```
fib <- function(i1, i2, n, theSum){
  iNext <- i1 + i2
  if(iNext < n){
    if(iNext %% 2  == 0){
      theSum <- theSum + iNext
    }
    return(fib(i2, iNext, n, theSum))
  }
  theSum
}
fib(1,2,4000000,2)
```

It's not very elegant. Perhaps it would be better to generate the fibonacci sequence and then do the sum separately. What do you think?

**Comment by thisisnic** [comment]
I like the idea of generating the fibonnaci sequence separately - if future Euler problems also the fibonnaci, might be useful to have some utility functions instead of repeating ourselves.
